INSERT INTO Yazarlar values(1,'Elif','Þafak')
INSERT INTO Yazarlar values(2,'Sabahattin','Ali')
INSERT INTO Yazarlar values(3,'Canan','Tan')
INSERT INTO Yazarlar values(4,'Ahmet ','Ümit')
INSERT INTO Yazarlar values(5,'Ýpek','Ongun')
INSERT INTO Yazarlar values(6,'Ayþe','Kulin')
INSERT INTO Yazarlar values(7,'Ýskender','Pala')
INSERT INTO Yazarlar values(8,'Zülfi','Livaneli')
INSERT INTO Yazarlar values(9,'Ömer','Seyfettin')
INSERT INTO Yazarlar values(10,'Sercan','Batman')
INSERT INTO Yazarlar values(11,'Peyami','Safa')